[build]
  # 构建命令（静态网站不需要构建）
  command = "echo 'Static website, no build needed'"
  
  # 发布目录
  publish = "."

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"

[[headers]]
  # 为所有路径设置缓存头
  for = "/*"
  [headers.values]
    # 缓存静态资源
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # HTML文件不缓存
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  # SPA重定向规则（如果需要）
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# 表单处理（如果需要添加联系表单）
# [[forms]]
#   name = "contact"